/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App {
  public static void main(String[] args) {

    java.util.Scanner key = new java.util.Scanner(System.in);

    int[] num = new int[20];
    String[] className = new String[20];
    String[] classContent = new String[20];
    String[] stDate = new String[20];
    String[] edDate = new String[20];
    int[] tot = new int[20];
    int[] day = new int[20];
    int i = 0;

    ok:{
      while(true) {
        String ans = null;
        System.out.print("번호 : ");
        num[i] = Integer.parseInt(key.nextLine());
        System.out.print("수업명 : ");
        className[i] = key.nextLine();
        System.out.print("수업내용 : ");
        classContent[i] = key.nextLine();
        System.out.print("시작일 : ");
        stDate[i] = key.nextLine();
        System.out.print("종료일 : ");
        edDate[i] = key.nextLine();
        System.out.print("총 수업시간 : ");
        tot[i] = Integer.parseInt(key.nextLine());
        System.out.print("일 수업시간 : ");
        day[i] = Integer.parseInt(key.nextLine());

        System.out.print("계속 입력하시겠습니까 y/n");
        ans = key.nextLine();

        if (ans.equals("y") || ans.equals("Y") || ans.equals("\n")) {
          i++;
          continue;
        } else {
          int j = 0;
          while (j <= i) {
            System.out.println(num[j]+" "+ className[j]+" "+ stDate[j] + " ~ "
                + edDate[j]+" "+tot[j]);
            j++;
          }
          break ok;
        }
      }
    }
















  }
}
