/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App {
    public static void main(String[] args) {
      System.out.println("번호 : "+1);
      System.out.println("수업명 :"+" 자바 프로젝트 실습");
      System.out.println("설명: 자바 프로젝트를 통한 자바 언어 활용법 익히기");
      System.out.print("시작일: 2019-01-02\n");
      System.out.printf("종료일: %s\n",2019-05-28);
      //pritnf(format, args) 아규먼트가 있을시 pritnf()사용
      //print, println ==just 줄바꿈 차이
      //printf는 print의 상위느낌..
      System.out.printf("총수업시간: %d 시간\n",1000);
      System.out.println("일수업시간: 8 시간");
      
      
      
      System.out.printf("asdad"+111111);
    }
}
