/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App {
    public static void main(String[] args) {
      java.util.Scanner key = new java.util.Scanner(System.in);
      
      System.out.print("번호 : ");
      int num = key.nextInt();
      
      key.nextLine();
      
      System.out.print("수업명 : ");
      String className = key.nextLine();
      
      System.out.print("수업내용 : ");
      String exp = key.nextLine();
      
      System.out.print("시작일 : ");
      String stDate = key.nextLine();
      
      System.out.print("종료일 : ");
      String edDate = key.nextLine();
      
      System.out.print("총수업시간 :");
      String totStudy = key.nextLine();
      
      System.out.print("일수업시간 : ");
      String dayStudy = key.nextLine();
      
      System.out.printf("번호 : %d\n수업명 : %s\n수업내용 : %s\n기간 : %s~"+"%s\n"
          + "총수업시간 : %s\n일수업시간 : %s\n",num , className, exp, stDate, edDate, totStudy, dayStudy);
      
      
    }
}
